volumes:
    mongodb_data:
    redis_data:

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb-ctnr
        ports:
          - "27017:27017"
        volumes:
          - mongodb_data:/data/db

    redis:
        image: redis:latest
        container_name: redis-ctnr
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data
